### ISSUE TITLE
navigator.clipboard is undefined 

### ISSUE THREAD

**Issue by iggant** [amatsuda/heavens_door#15]
Firefox Developer Edition 66.0 Beta 6 (20190207161357)

`TypeError: navigator.clipboard is undefined[Learn More] heavens_door.js:31:5`

when I type: 
`sessionStorage.heavensDoor`

It always return: 

```
"  scenario 'GENERATED' do
    visit '/whitelabels/clients/new'
"
```

**Comment by amatsuda** [comment]
It works with Firefox stable release on my machine.
If you're seeing that bug only on the Developer Edition, please try to debug your browser yourself, or report the bug to their bugzilla, or consider using stable software.

**Comment by brendanwb** [comment]
I was running into the same issue in multiple browsers (Safari, Chrome, and Firefox).  After some [research](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined), I found that `navigator.clipboard` is only available when the site you're browsing has a secure origin (https).  I switched my development environment to use https, and this fixed the issue for Firefox and Chrome.  According to [devdocs](https://devdocs.io/dom/clipboard_api), Safari is still implementing support.

**Comment by amatsuda** [comment]
@brendanwb Interesting. Is the situation same on a vanilla Rails app?
If not, you may be setting some kind of secure header on your app, and I suppose you could turn that off on development env.

**Comment by brendanwb** [comment]
@amatsuda it shouldn't matter what kind of Rails app, it's dependent on the browser.  If you go to any website using `https` and open the web inspector, `navigator.clipboard` is available.  If you go to any website that doesn't use `https`, Rails or otherwise, `navigator.clipboard` won't be available.

**Comment by paranishian** [comment]
I had the same problem, but in my case, it was because I was using lvh.me.

Browser: Chrome 78.0.3904.108（Official Build）

localhost:3000 | paranishian.lvh.me
---|---
![image](https://user-images.githubusercontent.com/1123224/70513622-5803f780-1b75-11ea-814f-a1e7de6981c5.png) | ![image](https://user-images.githubusercontent.com/1123224/70513602-520e1680-1b75-11ea-958f-bcee5f942190.png)
![image](https://user-images.githubusercontent.com/1123224/70513554-373ba200-1b75-11ea-889d-f281ba59f212.png) | ![image](https://user-images.githubusercontent.com/1123224/70513563-3c98ec80-1b75-11ea-958e-8c98d021389b.png)

**Comment by amatsuda** [comment]
@paranishian Thank you very much for a super helpful input!
Yes, the Clipboard API seems to be strictly limited to work only on localhost or over secure connection, and I haven't imagined using this gem outside of such environment.
Since lvh.me is something that I definitely want to support, I just pushed an adhoc patch fce8afc8b7f5564a154ed3a2a005740eb9664048 that falls back to good old legacy `execCommand("copy")` with a temporary dummy element for copying the content (I know this code is a mess, TBH I don't really want to maintain such a crap, but I couldn't come up with a better way doing this. Patches are welcome...).

**Comment by amatsuda** [comment]
Also, just published a new gem package with this change as version 0.3.0.
